# Header
menu:
  主页: /
  归档: /archives
  关于: /about
  微博: http://weibo.com/u/2952588044
  知乎: http://www.zhihu.com/people/tan-lin-quan
  GitHub: https://github.com/myqianlan
rss: /atom.xml

# Content
fancybox: false
mathjax: false

# Sidebar
sidebar: right
widgets:
- category
- tag
- tagcloud
- archive
- recent_posts
- links

# Links
links:
  主题作者: http://xiguabaobao.com
  热前端: http://reqianduan.com

# Miscellaneous
google_analytics: false
favicon: /img/favicon.ico
weibo: "myqianlan"
zhihu: "tan-lin-quan"
github: "myqianlan"

# Duoshuo
duoshuo_shortname: "myqianlan"

# Baidu share
baidushare: true