# Header
menu:
  主页: /
  归档: /archives
  关于: /about
  微博: http://weibo.com/u/2952588044
  GitHub: https://github.com/myqianlan
rss: /atom.xml

# Content
fancybox: true
mathjax: false

# Sidebar
sidebar: right
widgets:
- recent_posts
- category
- tag
#- tagcloud
- archive
- links

# Links
links:
  hexo: http://hexo.io/
  landscape-plus主题: https://github.com/xiangming/landscape-plus

# Miscellaneous
google_analytics: false
zhanzhang_tongji: true
favicon: /img/favicon.ico

# Duoshuo
duoshuo_shortname: "myqianlan"

# Baidu share
baidushare: true